# Generated by Django 5.0.6 on 2024-07-14 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_purchased', models.IntegerField(blank=True, default=0, null=True)),
                ('purchased_by', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('sold_by', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=100, null=True)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_csv', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.category')),
            ],
        ),
    ]
