# Generated by Django 5.0.6 on 2024-07-16 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_alter_stock_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_purchased', models.IntegerField(blank=True, default=0, null=True)),
                ('purchased_by', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('sold_by', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=100, null=True)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_app.category')),
            ],
        ),
    ]
